version: '3.2'
services:
  master:
    build: master/
    ports:
     - "8000:8000"
  worker:
    build: worker/
    environment:
      - MASTER_URI=http://master:8000
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    depends_on:
     - "master"
